rule R2Sign_Representative_Cabby {
    strings:
        $cabby__0cb17078bb20_text_10 = "hvS@" ascii
        $cabby__13ab04484839_text_10 = "hvS@" ascii
        $cabby__176f3ad6537a_text_10 = "hvS@" ascii
    condition:
        any of them
}
rule R2Sign_Representative_Fakeav {
    meta:
        description = "Generated by R2Sign Enhanced (with assembly comments)"
        author = "R2Sign Enhanced"
        date = "2026-09-04"
        version = "1.0"
        tool = "R2Sign + Radare2"
        performance_guidelines = "Neo23x0 YARA Performance Guidelines"
        target_type = "PE"
        pattern_count = 1
        avg_pattern_size = "8.0"
        confidence = "low"
        risk_level = "high"
        diversity_score = "1.00"
        payload_categories = "structural"
        pattern_types = "unknown"
        target_family = "malware"
        analysis_quality = "advanced"

    strings:
        $fakeav_func_0 = {
            8B FF 55 8B EC 83 EC [16-17] 00
        } // (low)

    condition:
1 of them
}
rule R2Sign_Representative_Kryptik {
    meta:
        description = "Generated by R2Sign Enhanced (with assembly comments)"
        author = "R2Sign Enhanced"
        date = "2026-09-04"
        version = "1.0"
        tool = "R2Sign + Radare2"
        performance_guidelines = "Neo23x0 YARA Performance Guidelines"
        target_type = "PE"
        pattern_count = 1
        avg_pattern_size = "11.0"
        confidence = "low"
        risk_level = "high"
        diversity_score = "1.00"
        payload_categories = "structural"
        pattern_types = "unknown"
        target_family = "malware"
        analysis_quality = "advanced"

    strings:
        $kryptik_func_0 = {
            55 8B EC 8B 45 08 8B 40 FC 5D C3
        } // (low)

    condition:
1 of them
}
rule R2Sign_Representative_Mediyes {
    meta:
        description = "Generated by R2Sign Enhanced (with assembly comments)"
        author = "R2Sign Enhanced"
        date = "2026-09-04"
        version = "1.0"
        tool = "R2Sign + Radare2"
        performance_guidelines = "Neo23x0 YARA Performance Guidelines"
        target_type = "PE"
        pattern_count = 2
        avg_pattern_size = "20.5"
        confidence = "low"
        risk_level = "very_low"
        diversity_score = "1.00"
        payload_categories = "structural"
        pattern_types = "unknown (x2)"
        target_family = "malware"
        analysis_quality = "advanced"

    strings:
        $mediyes_func_0 = {
            83 7C 24 08 01 75 05 E8 ?? ?? 00 00 FF 74 24 04 8B 4C 24 10 8B 54 24 0C E8 ED FE FF FF 59 C2 0C 00
        } // (low)
        $mediyes_func_1 = {
            56 8B F1 57 8B [1-2] 85 FF 74
        } // (low)

    condition:
2 of them
}
rule R2Sign_Representative_Sirefef {
    strings:
        $sirefef__4a9e7e209193_text_1608 = "9FT^" ascii
        $sirefef__659b7c3a6786_text_1004 = "4_AE" ascii
        $sirefef_af29c6d25d15_text_17 = "9FT^" ascii
    condition:
        any of them
}
rule R2Sign_Representative_Upatre {
    strings:
        $upatre__620bae1ab9de_text_130 = "edit" ascii
        $upatre__65d985debfd4_text_10 = "VWf9" ascii
        $upatre__6c9feb09c2f7_text_113 = "QRRh" ascii
    condition:
        any of them
}
rule R2Sign_Representative_Zbot {
    meta:
        description = "Generated by R2Sign Enhanced (with assembly comments)"
        author = "R2Sign Enhanced"
        date = "2026-09-04"
        version = "1.0"
        tool = "R2Sign + Radare2"
        performance_guidelines = "Neo23x0 YARA Performance Guidelines"
        target_type = "PE"
        pattern_count = 1
        avg_pattern_size = "11.0"
        confidence = "low"
        risk_level = "high"
        diversity_score = "1.00"
        payload_categories = "structural"
        pattern_types = "unknown"
        target_family = "malware"
        analysis_quality = "advanced"

    strings:
        $zbot_func_0 = {
            55 8B EC 8B 45 08 8B 40 FC 5D C3
        } // (low)

    condition:
1 of them
}
