rule fakeav_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-04"
        version = "1"
        description = "Describes fakeav."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/fakeav"
        malpedia_rule_date = "20260904"
        malpedia_hash = "4cbe151bb81cc690d7326ea68cf0d4b2edeb61e6"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 83c448 5d c3 8bff }
            // n = 4, score = 300
            //   83c448               | add                 esp, 0x48
            //   5d                   | pop                 ebp
            //   c3                   | ret
            //   8bff                 | mov                 edi, edi

        $sequence_1 = { e8???????? 83c410 5a 52 }
            // n = 4, score = 300
            //   e8????????           |
            //   83c410               | add                 esp, 0x10
            //   5a                   | pop                 edx
            //   52                   | push                edx

        $sequence_2 = { e8???????? 83c40c 5e 6a00 }
            // n = 4, score = 300
            //   e8????????           |
            //   83c40c               | add                 esp, 0xc
            //   5e                   | pop                 esi
            //   6a00                 | push                0

        $sequence_3 = { c3 8bff 55 8bec }
            // n = 4, score = 300
            //   c3                   | ret
            //   8bff                 | mov                 edi, edi
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp

        $sequence_4 = { 8bff 55 8bec 83ec5c }
            // n = 4, score = 300
            //   8bff                 | mov                 edi, edi
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp
            //   83ec5c               | sub                 esp, 0x5c

        $sequence_5 = { 83c410 5a 52 6a00 }
            // n = 4, score = 300
            //   83c410               | add                 esp, 0x10
            //   5a                   | pop                 edx
            //   52                   | push                edx
            //   6a00                 | push                0

        $sequence_6 = { 8bff 55 8bec 83ec44 }
            // n = 4, score = 300
            //   8bff                 | mov                 edi, edi
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp
            //   83ec44               | sub                 esp, 0x44

        $sequence_7 = { 8bff 55 8bec 83ec50 }
            // n = 4, score = 300
            //   8bff                 | mov                 edi, edi
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp
            //   83ec50               | sub                 esp, 0x50

        $sequence_8 = { e8???????? 83c40c 59 51 }
            // n = 4, score = 300
            //   e8????????           |
            //   83c40c               | add                 esp, 0xc
            //   59                   | pop                 ecx
            //   51                   | push                ecx

        $sequence_9 = { 8bff 55 8bec 83ec30 }
            // n = 4, score = 300
            //   8bff                 | mov                 edi, edi
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp
            //   83ec30               | sub                 esp, 0x30

    condition:
        7 of them and filesize < 2334720
}rule kryptik_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-04"
        version = "1"
        description = "Describes kryptik."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/kryptik"
        malpedia_rule_date = "20260904"
        malpedia_hash = "4cbe151bb81cc690d7326ea68cf0d4b2edeb61e6"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 51 8b5510 52 8b450c }
            // n = 4, score = 300
            //   51                   | push                ecx
            //   8b5510               | mov                 edx, dword ptr [ebp + 0x10]
            //   52                   | push                edx
            //   8b450c               | mov                 eax, dword ptr [ebp + 0xc]

        $sequence_1 = { 68???????? ff15???????? 6a00 6880000000 }
            // n = 4, score = 300
            //   68????????           |
            //   ff15????????         |
            //   6a00                 | push                0
            //   6880000000           | push                0x80

        $sequence_2 = { c745fc00000000 eb09 8b45fc 83c001 }
            // n = 4, score = 300
            //   c745fc00000000       | mov                 dword ptr [ebp - 4], 0
            //   eb09                 | jmp                 0xb
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]
            //   83c001               | add                 eax, 1

        $sequence_3 = { 6a00 6a03 6a01 68???????? }
            // n = 4, score = 300
            //   6a00                 | push                0
            //   6a03                 | push                3
            //   6a01                 | push                1
            //   68????????           |

        $sequence_4 = { eb09 8b45fc 83c001 8945fc }
            // n = 4, score = 300
            //   eb09                 | jmp                 0xb
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]
            //   83c001               | add                 eax, 1
            //   8945fc               | mov                 dword ptr [ebp - 4], eax

        $sequence_5 = { 51 8b55f4 52 e8???????? }
            // n = 4, score = 300
            //   51                   | push                ecx
            //   8b55f4               | mov                 edx, dword ptr [ebp - 0xc]
            //   52                   | push                edx
            //   e8????????           |

        $sequence_6 = { 8b45fc 83c001 8945fc 8b4dfc }
            // n = 4, score = 300
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]
            //   83c001               | add                 eax, 1
            //   8945fc               | mov                 dword ptr [ebp - 4], eax
            //   8b4dfc               | mov                 ecx, dword ptr [ebp - 4]

        $sequence_7 = { 8b4508 8b4d08 034804 894d08 }
            // n = 4, score = 300
            //   8b4508               | mov                 eax, dword ptr [ebp + 8]
            //   8b4d08               | mov                 ecx, dword ptr [ebp + 8]
            //   034804               | add                 ecx, dword ptr [eax + 4]
            //   894d08               | mov                 dword ptr [ebp + 8], ecx

        $sequence_8 = { 6a03 6a00 6a03 6a01 }
            // n = 4, score = 300
            //   6a03                 | push                3
            //   6a00                 | push                0
            //   6a03                 | push                3
            //   6a01                 | push                1

        $sequence_9 = { 6880000000 6a03 6a00 6a03 }
            // n = 4, score = 300
            //   6880000000           | push                0x80
            //   6a03                 | push                3
            //   6a00                 | push                0
            //   6a03                 | push                3

    condition:
        7 of them and filesize < 306176
}rule mediyes_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-04"
        version = "1"
        description = "Describes mediyes."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/mediyes"
        malpedia_rule_date = "20260904"
        malpedia_hash = "4cbe151bb81cc690d7326ea68cf0d4b2edeb61e6"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 6afe 5e 33d2 b9???????? }
            // n = 4, score = 300
            //   6afe                 | push                -2
            //   5e                   | pop                 esi
            //   33d2                 | xor                 edx, edx
            //   b9????????           |

        $sequence_1 = { 895f24 897720 57 66897710 }
            // n = 4, score = 300
            //   895f24               | mov                 dword ptr [edi + 0x24], ebx
            //   897720               | mov                 dword ptr [edi + 0x20], esi
            //   57                   | push                edi
            //   66897710             | mov                 word ptr [edi + 0x10], si

        $sequence_2 = { 8b44240c 81480c00800000 59 c3 }
            // n = 4, score = 300
            //   8b44240c             | mov                 eax, dword ptr [esp + 0xc]
            //   81480c00800000       | or                  dword ptr [eax + 0xc], 0x8000
            //   59                   | pop                 ecx
            //   c3                   | ret

        $sequence_3 = { 8b4c2404 8901 33c0 c3 }
            // n = 4, score = 300
            //   8b4c2404             | mov                 ecx, dword ptr [esp + 4]
            //   8901                 | mov                 dword ptr [ecx], eax
            //   33c0                 | xor                 eax, eax
            //   c3                   | ret

        $sequence_4 = { 5e c3 e8???????? 56 }
            // n = 4, score = 300
            //   5e                   | pop                 esi
            //   c3                   | ret
            //   e8????????           |
            //   56                   | push                esi

        $sequence_5 = { 8bec 83e4f8 83ec14 8b4104 }
            // n = 4, score = 300
            //   8bec                 | mov                 ebp, esp
            //   83e4f8               | and                 esp, 0xfffffff8
            //   83ec14               | sub                 esp, 0x14
            //   8b4104               | mov                 eax, dword ptr [ecx + 4]

        $sequence_6 = { 83f803 7cf4 33c0 e9???????? }
            // n = 4, score = 300
            //   83f803               | cmp                 eax, 3
            //   7cf4                 | jl                  0xfffffff6
            //   33c0                 | xor                 eax, eax
            //   e9????????           |

        $sequence_7 = { 51 50 ffd6 85c0 }
            // n = 4, score = 300
            //   51                   | push                ecx
            //   50                   | push                eax
            //   ffd6                 | call                esi
            //   85c0                 | test                eax, eax

        $sequence_8 = { 5e c9 c20400 56 }
            // n = 4, score = 300
            //   5e                   | pop                 esi
            //   c9                   | leave
            //   c20400               | ret                 4
            //   56                   | push                esi

        $sequence_9 = { ff7104 e8???????? 59 c3 }
            // n = 4, score = 300
            //   ff7104               | push                dword ptr [ecx + 4]
            //   e8????????           |
            //   59                   | pop                 ecx
            //   c3                   | ret

    condition:
        7 of them and filesize < 966656
}rule sirefef_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-04"
        version = "1"
        description = "Describes sirefef."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/sirefef"
        malpedia_rule_date = "20260904"
        malpedia_hash = "4cbe151bb81cc690d7326ea68cf0d4b2edeb61e6"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 49 8b45e4 0fafc1 2be0 }
            // n = 4, score = 300
            //   49                   | dec                 ecx
            //   8b45e4               | mov                 eax, dword ptr [ebp - 0x1c]
            //   0fafc1               | imul                eax, ecx
            //   2be0                 | sub                 esp, eax

        $sequence_1 = { 0fafc1 03e0 92 50 }
            // n = 4, score = 300
            //   0fafc1               | imul                eax, ecx
            //   03e0                 | add                 esp, eax
            //   92                   | xchg                edx, eax
            //   50                   | push                eax

        $sequence_2 = { 0f850d000000 8b0d???????? 49 890d???????? }
            // n = 4, score = 300
            //   0f850d000000         | jne                 0x13
            //   8b0d????????         |
            //   49                   | dec                 ecx
            //   890d????????         |

        $sequence_3 = { 92 50 33db 8bd4 }
            // n = 4, score = 300
            //   92                   | xchg                edx, eax
            //   50                   | push                eax
            //   33db                 | xor                 ebx, ebx
            //   8bd4                 | mov                 edx, esp

        $sequence_4 = { 8125????????00000000 e9???????? 8b0d???????? 41 }
            // n = 4, score = 300
            //   8125????????00000000     |
            //   e9????????           |
            //   8b0d????????         |
            //   41                   | inc                 ecx

        $sequence_5 = { 0f850d000000 8b0d???????? 41 890d???????? }
            // n = 4, score = 300
            //   0f850d000000         | jne                 0x13
            //   8b0d????????         |
            //   41                   | inc                 ecx
            //   890d????????         |

        $sequence_6 = { 33d2 0315???????? 42 8915???????? }
            // n = 4, score = 300
            //   33d2                 | xor                 edx, edx
            //   0315????????         |
            //   42                   | inc                 edx
            //   8915????????         |

        $sequence_7 = { 49 890d???????? 8b0d???????? 49 }
            // n = 4, score = 300
            //   49                   | dec                 ecx
            //   890d????????         |
            //   8b0d????????         |
            //   49                   | dec                 ecx

        $sequence_8 = { 8125????????00000000 e9???????? 8b35???????? 46 }
            // n = 4, score = 300
            //   8125????????00000000     |
            //   e9????????           |
            //   8b35????????         |
            //   46                   | inc                 esi

        $sequence_9 = { 0f8408000000 8b4508 e9???????? 8b45fc }
            // n = 4, score = 300
            //   0f8408000000         | je                  0xe
            //   8b4508               | mov                 eax, dword ptr [ebp + 8]
            //   e9????????           |
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]

    condition:
        7 of them and filesize < 569344
}rule upatre_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-04"
        version = "1"
        description = "Describes upatre."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/upatre"
        malpedia_rule_date = "20260904"
        malpedia_hash = "4cbe151bb81cc690d7326ea68cf0d4b2edeb61e6"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 47 4e 49 75f7 }
            // n = 4, score = 300
            //   47                   | inc                 edi
            //   4e                   | dec                 esi
            //   49                   | dec                 ecx
            //   75f7                 | jne                 0xfffffff9

        $sequence_1 = { 8a06 8807 46 47 }
            // n = 4, score = 300
            //   8a06                 | mov                 al, byte ptr [esi]
            //   8807                 | mov                 byte ptr [edi], al
            //   46                   | inc                 esi
            //   47                   | inc                 edi

        $sequence_2 = { 49 75f7 8b35???????? 8b0d???????? }
            // n = 4, score = 300
            //   49                   | dec                 ecx
            //   75f7                 | jne                 0xfffffff9
            //   8b35????????         |
            //   8b0d????????         |

        $sequence_3 = { 0fb60a 85c9 7408 51 }
            // n = 4, score = 300
            //   0fb60a               | movzx               ecx, byte ptr [edx]
            //   85c9                 | test                ecx, ecx
            //   7408                 | je                  0xa
            //   51                   | push                ecx

        $sequence_4 = { 03ce 890d???????? 59 8b06 }
            // n = 4, score = 300
            //   03ce                 | add                 ecx, esi
            //   890d????????         |
            //   59                   | pop                 ecx
            //   8b06                 | mov                 eax, dword ptr [esi]

        $sequence_5 = { ebf0 33c0 40 5f }
            // n = 4, score = 300
            //   ebf0                 | jmp                 0xfffffff2
            //   33c0                 | xor                 eax, eax
            //   40                   | inc                 eax
            //   5f                   | pop                 edi

        $sequence_6 = { 6840010000 6a0a 6a0a 6801000010 }
            // n = 4, score = 300
            //   6840010000           | push                0x140
            //   6a0a                 | push                0xa
            //   6a0a                 | push                0xa
            //   6801000010           | push                0x10000001

        $sequence_7 = { 46 90 46 46 }
            // n = 4, score = 300
            //   46                   | inc                 esi
            //   90                   | nop
            //   46                   | inc                 esi
            //   46                   | inc                 esi

        $sequence_8 = { 8945fc 4e 4e 0fb71e }
            // n = 4, score = 300
            //   8945fc               | mov                 dword ptr [ebp - 4], eax
            //   4e                   | dec                 esi
            //   4e                   | dec                 esi
            //   0fb71e               | movzx               ebx, word ptr [esi]

        $sequence_9 = { 47 47 47 42 }
            // n = 4, score = 300
            //   47                   | inc                 edi
            //   47                   | inc                 edi
            //   47                   | inc                 edi
            //   42                   | inc                 edx

    condition:
        7 of them and filesize < 67584
}rule zbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-04"
        version = "1"
        description = "Describes zbot."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/zbot"
        malpedia_rule_date = "20260904"
        malpedia_hash = "4cbe151bb81cc690d7326ea68cf0d4b2edeb61e6"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 740f 6a04 ff15???????? 33c0 }
            // n = 4, score = 300
            //   740f                 | je                  0x11
            //   6a04                 | push                4
            //   ff15????????         |
            //   33c0                 | xor                 eax, eax

        $sequence_1 = { 83c004 8945f4 8b4df4 3b4d0c }
            // n = 4, score = 300
            //   83c004               | add                 eax, 4
            //   8945f4               | mov                 dword ptr [ebp - 0xc], eax
            //   8b4df4               | mov                 ecx, dword ptr [ebp - 0xc]
            //   3b4d0c               | cmp                 ecx, dword ptr [ebp + 0xc]

        $sequence_2 = { c6420b74 a1???????? c6400c6c 8b0d???????? }
            // n = 4, score = 300
            //   c6420b74             | mov                 byte ptr [edx + 0xb], 0x74
            //   a1????????           |
            //   c6400c6c             | mov                 byte ptr [eax + 0xc], 0x6c
            //   8b0d????????         |

        $sequence_3 = { e9???????? 8d8dd8feffff 51 6819000200 }
            // n = 4, score = 300
            //   e9????????           |
            //   8d8dd8feffff         | lea                 ecx, [ebp - 0x128]
            //   51                   | push                ecx
            //   6819000200           | push                0x20019

        $sequence_4 = { c641106c 8b15???????? c6025c a1???????? }
            // n = 4, score = 300
            //   c641106c             | mov                 byte ptr [ecx + 0x10], 0x6c
            //   8b15????????         |
            //   c6025c               | mov                 byte ptr [edx], 0x5c
            //   a1????????           |

        $sequence_5 = { 83c40c 8b45fc 2d???????? 50 }
            // n = 4, score = 300
            //   83c40c               | add                 esp, 0xc
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]
            //   2d????????           |
            //   50                   | push                eax

        $sequence_6 = { 8b4508 034204 894508 e9???????? }
            // n = 4, score = 300
            //   8b4508               | mov                 eax, dword ptr [ebp + 8]
            //   034204               | add                 eax, dword ptr [edx + 4]
            //   894508               | mov                 dword ptr [ebp + 8], eax
            //   e9????????           |

        $sequence_7 = { 8b15???????? c6420565 a1???????? c640066d }
            // n = 4, score = 300
            //   8b15????????         |
            //   c6420565             | mov                 byte ptr [edx + 5], 0x65
            //   a1????????           |
            //   c640066d             | mov                 byte ptr [eax + 6], 0x6d

        $sequence_8 = { 6a00 68???????? 8b95d8feffff 52 }
            // n = 4, score = 300
            //   6a00                 | push                0
            //   68????????           |
            //   8b95d8feffff         | mov                 edx, dword ptr [ebp - 0x128]
            //   52                   | push                edx

        $sequence_9 = { 8d85d8feffff 50 6819000200 6a00 }
            // n = 4, score = 300
            //   8d85d8feffff         | lea                 eax, [ebp - 0x128]
            //   50                   | push                eax
            //   6819000200           | push                0x20019
            //   6a00                 | push                0

    condition:
        7 of them and filesize < 592896
}