rule R2Sign_Generated_Enhanced {
    meta:
        description = "Generated by R2Sign Enhanced (with assembly comments)"
        author = "R2Sign Enhanced"
        date = "2026-09-04"
        version = "1.0"
        tool = "R2Sign + Radare2"
        performance_guidelines = "Neo23x0 YARA Performance Guidelines"
        target_type = "PE"
        pattern_count = 1
        avg_pattern_size = "11.0"
        confidence = "low"
        risk_level = "high"
        diversity_score = "1.00"
        payload_categories = "structural"
        pattern_types = "unknown"
        target_family = "malware"
        analysis_quality = "advanced"

    strings:
        $func_0 = {
            8B 65 E8 FF 75 98 E8 25 0D 00 00
        } // (low)

    condition:
1 of them
}
