rule mediyes_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-08-30"
        version = "1"
        description = "Describes mediyes."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0-source"
        signator_config = "dummy"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/mediyes"
        malpedia_rule_date = "2026-08-30"
        malpedia_hash = "local-r2sign-corpus"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 014dfc 837dfc00 0f8ea5000000 8b7dfc }
            // n = 4, score = 300
            //   014dfc               | add                 dword ptr [ebp - 4], ecx
            //   837dfc00             | cmp                 dword ptr [ebp - 4], 0
            //   0f8ea5000000         | jle                 0xab
            //   8b7dfc               | mov                 edi, dword ptr [ebp - 4]

        $sequence_1 = { 02db d0fb 80fb02 897590 }
            // n = 4, score = 300
            //   02db                 | add                 bl, bl
            //   d0fb                 | sar                 bl, 1
            //   80fb02               | cmp                 bl, 2
            //   897590               | mov                 dword ptr [ebp - 0x70], esi

        $sequence_2 = { 01442460 894614 8a2f 8a4f01 }
            // n = 4, score = 300
            //   01442460             | add                 dword ptr [esp + 0x60], eax
            //   894614               | mov                 dword ptr [esi + 0x14], eax
            //   8a2f                 | mov                 ch, byte ptr [edi]
            //   8a4f01               | mov                 cl, byte ptr [edi + 1]

        $sequence_3 = { 02e6 3ac7 7206 3ac3 }
            // n = 4, score = 300
            //   02e6                 | add                 ah, dh
            //   3ac7                 | cmp                 al, bh
            //   7206                 | jb                  8
            //   3ac3                 | cmp                 al, bl

        $sequence_4 = { 014c2460 895610 8b442414 83c001 }
            // n = 4, score = 300
            //   014c2460             | add                 dword ptr [esp + 0x60], ecx
            //   895610               | mov                 dword ptr [esi + 0x10], edx
            //   8b442414             | mov                 eax, dword ptr [esp + 0x14]
            //   83c001               | add                 eax, 1

        $sequence_5 = { 017008 834010ff 7558 8b4804 }
            // n = 4, score = 300
            //   017008               | add                 dword ptr [eax + 8], esi
            //   834010ff             | add                 dword ptr [eax + 0x10], -1
            //   7558                 | jne                 0x5a
            //   8b4804               | mov                 ecx, dword ptr [eax + 4]

        $sequence_6 = { 0303 0302 0303 0303 }
            // n = 4, score = 300
            //   0303                 | add                 eax, dword ptr [ebx]
            //   0302                 | add                 eax, dword ptr [edx]
            //   0303                 | add                 eax, dword ptr [ebx]
            //   0303                 | add                 eax, dword ptr [ebx]

        $sequence_7 = { 0145a0 3bc3 0f8c1f010000 8b45ac }
            // n = 4, score = 300
            //   0145a0               | add                 dword ptr [ebp - 0x60], eax
            //   3bc3                 | cmp                 eax, ebx
            //   0f8c1f010000         | jl                  0x125
            //   8b45ac               | mov                 eax, dword ptr [ebp - 0x54]

        $sequence_8 = { 02c6 3ae0 750b 83e901 }
            // n = 4, score = 300
            //   02c6                 | add                 al, dh
            //   3ae0                 | cmp                 ah, al
            //   750b                 | jne                 0xd
            //   83e901               | sub                 ecx, 1

        $sequence_9 = { 0175a4 0175a4 668910 03c6 }
            // n = 4, score = 300
            //   0175a4               | add                 dword ptr [ebp - 0x5c], esi
            //   0175a4               | add                 dword ptr [ebp - 0x5c], esi
            //   668910               | mov                 word ptr [eax], dx
            //   03c6                 | add                 eax, esi

    condition:
        7 of them and filesize < 475136
}